"""S6-02 Tauri packaging and default-deny desktop bridge checks."""

from __future__ import annotations

import json
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DESKTOP = ROOT / "clients/desktop"
TAURI = DESKTOP / "src-tauri"


def test_desktop_manifests_pin_the_approved_direct_dependencies() -> None:
    package = json.loads((DESKTOP / "package.json").read_text(encoding="utf-8"))
    cargo = tomllib.loads((TAURI / "Cargo.toml").read_text(encoding="utf-8"))
    toolchain = tomllib.loads((DESKTOP / "rust-toolchain.toml").read_text(encoding="utf-8"))

    assert package["private"] is True
    assert package["devDependencies"] == {"@tauri-apps/cli": "2.11.4"}
    assert package["scripts"] == {
        "desktop:build": "tauri build --no-bundle",
        "desktop:check": "tauri info",
        "desktop:dev": "tauri dev",
        "desktop:test": "node --test tests/desktop-status.test.js",
    }
    assert toolchain["toolchain"] == {
        "channel": "1.98.0",
        "components": ["clippy", "rustfmt"],
        "profile": "minimal",
        "targets": ["x86_64-pc-windows-msvc"],
    }
    assert cargo["build-dependencies"] == {"tauri-build": {"features": [], "version": "=2.6.3"}}
    assert cargo["dependencies"] == {
        "serde": {"features": ["derive"], "version": "=1.0.229"},
        "serde_json": {"version": "=1.0.151"},
        "sha2": {"version": "=0.11.0"},
        "tauri": {"features": [], "version": "=2.11.5"},
        "uuid": {"features": ["serde"], "version": "=1.25.0"},
    }
    assert (DESKTOP / "package-lock.json").is_file()
    assert (TAURI / "Cargo.lock").is_file()


def test_tauri_configuration_is_local_explicit_and_default_deny() -> None:
    config = json.loads((TAURI / "tauri.conf.json").read_text(encoding="utf-8"))
    capability = json.loads((TAURI / "capabilities/desktop-main.json").read_text(encoding="utf-8"))

    assert config["build"] == {"frontendDist": "../frontend"}
    assert config["app"]["withGlobalTauri"] is True
    assert config["app"]["security"]["capabilities"] == ["desktop-main"]
    assert "connect-src 'none'" in config["app"]["security"]["csp"]
    assert config["app"]["windows"] == [
        {
            "center": True,
            "height": 760,
            "label": "main",
            "minHeight": 640,
            "minWidth": 900,
            "resizable": True,
            "title": "NDT Agent Desktop",
            "width": 1180,
        }
    ]
    assert config["bundle"]["active"] is False
    assert capability["windows"] == ["main"]
    assert capability["local"] is True
    assert "remote" not in capability
    assert capability["permissions"] == ["allow-desktop-bridge-status"]


def test_native_bridge_exposes_no_shell_network_or_client_owned_authority() -> None:
    build_script = (TAURI / "build.rs").read_text(encoding="utf-8")
    bridge = (TAURI / "src/bridge.rs").read_text(encoding="utf-8")
    library = (TAURI / "src/lib.rs").read_text(encoding="utf-8")
    invoke_permission = (TAURI / "permissions/autogenerated/desktop_bridge_invoke.toml").read_text(
        encoding="utf-8"
    )
    status_permission = (TAURI / "permissions/autogenerated/desktop_bridge_status.toml").read_text(
        encoding="utf-8"
    )
    combined = "\n".join((build_script, bridge, library)).lower()

    assert ".commands(" in build_script
    assert '"desktop_bridge_status"' in build_script
    assert '"desktop_bridge_invoke"' in build_script
    assert 'commands.allow = ["desktop_bridge_status"]' in status_permission
    assert 'commands.allow = ["desktop_bridge_invoke"]' in invoke_permission
    assert "deny_unknown_fields" in bridge
    assert "desktop_session_required" in bridge.lower()
    assert "desktop_executor_unavailable" in bridge.lower()
    assert "std::process" not in combined
    assert "command::new" not in combined
    assert "powershell" not in combined
    assert "cmd.exe" not in combined
    assert "shell::" not in combined
    assert "reqwest" not in combined
    assert "std::net" not in combined
    assert "std::fs::write" not in combined
    assert "approved_call_sha256s" not in bridge
    assert "granted_permissions" not in bridge


def test_desktop_frontend_is_static_safe_and_status_only() -> None:
    shell = (DESKTOP / "frontend/index.html").read_text(encoding="utf-8")
    script = (DESKTOP / "frontend/desktop.js").read_text(encoding="utf-8")
    behavior_tests = (DESKTOP / "tests/desktop-status.test.js").read_text(encoding="utf-8")
    styles = (DESKTOP / "frontend/desktop.css").read_text(encoding="utf-8")

    assert "NDT Agent Desktop" in shell
    assert "Local adapter execution unavailable" in shell
    assert 'invoke("desktop_bridge_status")' in script
    assert "desktop_bridge_invoke" not in script
    assert "innerHTML" not in script
    assert "localStorage" not in script
    assert "sessionStorage" not in script
    assert "fetch(" not in script
    assert "desktop_bridge_status" in behavior_tests
    assert "DESKTOP_SESSION_REQUIRED" in behavior_tests
    assert "provider detail must not be rendered" in behavior_tests
    assert "@media (max-width: 760px)" in styles
    assert "prefers-reduced-motion" in styles


def test_desktop_contract_is_ascii_and_names_remaining_release_limits() -> None:
    contract = (ROOT / "docs/contracts/desktop-client-v1.md").read_text(encoding="ascii")
    for marker in (
        "DESKTOP_SESSION_REQUIRED",
        "DESKTOP_EXECUTOR_UNAVAILABLE",
        "default-deny",
        "signing",
        "upgrade",
        "rollback",
    ):
        assert marker in contract
